[general]
language = "en"
theme = "system"
onstartup = false
startuptype = "minimized"
interactiveselect = true
selectedarea = "0x0x0x0"
selectedprofile = "default"
selectedproject = "default"
selectedgroup = "default"

[general.annotation]
editortype = "buildin"
editorpath = ""

[general.backup]
automatic = false
frequency = 7
keep = 1
path = ""

[ocr]
installation = "system"
path = ""
language = "eng"

[shortcuts]

[shortcuts.screenshots]
everything = "Ctrl+Alt+Ins"
selectedarea = ""
selectarea = ""
area = "Meta+Ctrl+Ins"

[shortcuts.windows]
openmain = ""
openproject = ""
openview = ""
